version: '3.8'

services:
  backend:
    build: .
    ports:
      - '5000:5000'
    env_file:
      - .env
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - '27017:27017'
